dataset:
  path: "datasets/dataset.csv"
  format: csv
  delimiter: ","

input_features:
  - name: text
    type: text
    encoder: roberta

output_features:
  - name: sentiment
    type: category
    num_classes: 3

training:
  epochs: 5
  batch_size: 32
  optimizer: adam
  loss: sparse_categorical_crossentropy

preprocessing:
  split:
    train: 0.7
    test: 0.2
    validation: 0.1
    random_seed: 42
  text:
    lower_case: true
    remove_punctuation: true
    remove_stopwords: true
    stemming: false
    tokenization:
      method: word

model:
  encoder: rnn  # or cnn_parallel, cnn_stacked, rnn
  params:
    vocab_size: 5000
    embedding_size: 128
    state_size: 64
    num_layers: 2
    cell_type: lstm  # or rnn, gru
    bidirectional: false
    representation: concat  # or sum, average
    recurrent_dropout: 0.2
    recurrent_initializer: glorot_uniform
    use_bias: true
    weights_initializer: glorot_uniform
    unit_forget_bias: true
    reduce_output: true
    num_fc_layers: 2
    norm: batch
    output_size: 3
