dataset:
  path: "datasets/dataset.csv"
  format: csv
  delimiter: ","

input_features:
  - name: text
    type: text
    encoder: roberta

output_features:
  - name: sentiment
    type: category
    num_classes: 3

training:
  epochs: 5
  batch_size: 32


preprocessing:
  split:
    train: 0.7
    test: 0.2
    validation: 0.1
    random_seed: 42
  text:
    lower_case: true
    remove_punctuation: true
    remove_stopwords: true
    stemming: false
    tokenization:
      method: word